<?php $return = $this->return; ?>
<div class="row">
    <div class="col-md-12">
        <section class="widget">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->url('admin'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li><a href="<?php echo $this->url('admin/playgroundcmsadmin/template'); ?>"><i class="fa fa-align-justify"></i> Templates</a></li>
                <li class="active">Edit a template : <?php echo $template->getName(); ?></li>
            </ol>
        </section>
        <h2 class="page-title"><i class="fa fa-align-justify"></i> Edit a template : <?php echo $template->getName(); ?></h2>
    </div>
</div>
<form method="POST" ENCTYPE="multipart/form-data">
    <input type="text" id="templateId" name="template[id]" class="form-control hide" value="<?php echo $template->getId()?>" >

<?php if(!empty($return) && $return['status'] != 0) : ?>
    <div class="row">
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="fa fa-ban"></i> <strong><?php echo $return['message'];?>!</strong></h4>
        </div>
    </div>
<?php endif; ?>
<div class="row">
    <div class="col-md-6">
        <section class="widget">
            <header>
                <h4>Template informations</h4>
            </header>
            <div class="body">
                <div id="page-options" class="form-horizontal form-condensed label-left">
                    <fieldset>
                        <div class="form-horizontal" method="post" novalidate="novalidate" data-validate="parsley">
                            <div class="control-group">
                                <label for="description" class="control-label">Name <span class="required">*</span></label>
                                <div class="controls form-group">
                                    <input type="text" id="first-name" name="template[name]" class="form-control" value="<?php echo $template->getName(); ?>" />
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="description" class="control-label">Description</label>
                                <div class="controls form-group">
                                    <textarea id="description" rows="3" name="template[description]" class="form-control"><?php echo $template->getDescription();?></textarea>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="description" class="control-label">Template File <span class="required">*</span></label>
                                <div class="controls form-group">
                                    <select class="selectpicker show-tick" name="template[file]" data-live-search="true" data-size="6" data-width="100%">
                                        <option value="" data-content="">Choose the template</option>
                                        <?php foreach ($this->files as $file) : ?>
                                            <option value="<?php echo $file ?>" <?php echo $template->getFile()==$file?'selected':'';?>><?php echo $file; ?></option>
                                        <?php endforeach; ?>
                                  </select>
                                  <span class="help-block">All .phtml templates in active frontend theme</span>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </section>
        <section class="widget">
            <header>
                <h4>Template associations</h4>
            </header>
            <div class="body">
                <div id="page-options" class="form-horizontal form-condensed label-left">
                    <fieldset>
                        <div class="form-horizontal" method="post" novalidate="novalidate" data-validate="parsley">
                            <div class="control-group">
                                <label for="description" class="control-label">Block Type</label>
                                <div class="controls form-group">
                                    <select class="selectpicker show-tick"  name="template[block_type]" data-live-search="true" data-size="6" data-width="100%">
                                        <option value="" data-content="">Choose the block type</option>
                                        <?php foreach ($this->blockstype as $blocktype) : ?>
                                            <option value="<?php echo $blocktype ?>" <?php echo $template->getBlockType()==$blocktype?'selected':'';?>><?php echo $blocktype; ?></option>
                                        <?php endforeach; ?>
                                  </select>
                                  <span class="help-block">Associate a template to a block type</span>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="text" class="control-label">System Template ? <span class="required">*</span></label>
                                <div class="controls form-group">
                                    <div class="btn-group" data-toggle="buttons">
                                        <label class="radio">
                                        <input type="radio" class="icheck" name="template[system]" value="1" <?php echo $template->getIsSystem()=="1"?'checked':'';?>>
                                        Yes
                                    </label>
                                    <label class="radio">
                                        <input type="radio" class="icheck" name="template[system]" value="0" <?php echo $template->getIsSystem()==0?'checked':'';?>>
                                        No
                                    </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </section>
    </div>
    <div class="col-md-6">
        <section class="widget">
            <header>
                <h4><i class="fa fa-picture-o"></i> Picture</h4>
            </header>
            <div class="body">
                <div id="page-options" class="form-horizontal form-condensed label-left">
                    <div class="thumbnail">
                        <?php $image = $template->getImage(); ?>
                        <?php if(!empty($image)) : ?>
                            <img src="<?php echo $image; ?>" alt="<?php echo $template->getName(); ?>">
                        <?php endif; ?>
                        <div class="caption">

                            <p><?php echo $template->getImage(); ?></p>
                            <p>
                                <div class="control-group">
                                    <div class="input-group">
                                        <span class="btn btn-sm btn-default fileinput-button">
                                            <i class="fa fa-plus"></i>
                                            <span>Add a media</span>
                                            <input type="file" name="files" />
                                        </span>
                                    </div>
                                </div>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="widget">
            <header>
                <h4><i class="fa fa-plus"></i> Actions</h4>
            </header>
            <div class="body">
                <button type="submit" class="btn btn-success pull-right">Submit</button>
                <div class="clearfix">&nbsp;</div>
            </div>
        </section>
    </div>
</div>
</form>